// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ecs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadEcsInject returns the embedded CollectionSpec for EcsInject.
func LoadEcsInject() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EcsInjectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load EcsInject: %w", err)
	}

	return spec, err
}

// LoadEcsInjectObjects loads EcsInject and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EcsInjectObjects
//	*EcsInjectPrograms
//	*EcsInjectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEcsInjectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEcsInject()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EcsInjectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EcsInjectSpecs struct {
	EcsInjectProgramSpecs
	EcsInjectMapSpecs
	EcsInjectVariableSpecs
}

// EcsInjectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EcsInjectProgramSpecs struct {
	InjectEcs *ebpf.ProgramSpec `ebpf:"inject_ecs"`
}

// EcsInjectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EcsInjectMapSpecs struct {
}

// EcsInjectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EcsInjectVariableSpecs struct {
}

// EcsInjectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEcsInjectObjects or ebpf.CollectionSpec.LoadAndAssign.
type EcsInjectObjects struct {
	EcsInjectPrograms
	EcsInjectMaps
	EcsInjectVariables
}

func (o *EcsInjectObjects) Close() error {
	return _EcsInjectClose(
		&o.EcsInjectPrograms,
		&o.EcsInjectMaps,
	)
}

// EcsInjectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEcsInjectObjects or ebpf.CollectionSpec.LoadAndAssign.
type EcsInjectMaps struct {
}

func (m *EcsInjectMaps) Close() error {
	return _EcsInjectClose()
}

// EcsInjectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEcsInjectObjects or ebpf.CollectionSpec.LoadAndAssign.
type EcsInjectVariables struct {
}

// EcsInjectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEcsInjectObjects or ebpf.CollectionSpec.LoadAndAssign.
type EcsInjectPrograms struct {
	InjectEcs *ebpf.Program `ebpf:"inject_ecs"`
}

func (p *EcsInjectPrograms) Close() error {
	return _EcsInjectClose(
		p.InjectEcs,
	)
}

func _EcsInjectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ecsinject_bpfeb.o
var _EcsInjectBytes []byte
